# Generated by Django 5.2 on 2025-05-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('learning_goal', models.TextField(blank=True, null=True)),
                ('background', models.CharField(blank=True, max_length=100, null=True)),
                ('time_commitment', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_style', models.CharField(blank=True, max_length=100, null=True)),
                ('path_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='api.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
