# Generated by Django 5.2 on 2025-05-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_student_bio_student_github_url_student_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_item_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
