# Generated by Django 5.2 on 2025-05-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='course_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
