# Generated by Django 5.2 on 2025-05-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_notification_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
